language: objective-c
osx_image: xcode12.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=OAuthSwift.xcodeproj
    - IOS_FRAMEWORK_SCHEME="OAuthSwift"
    - MACOS_FRAMEWORK_SCHEME="OAuthSwiftMacOS"
    - IOS_SDK=iphonesimulator14.2
    - MACOS_SDK=macosx11.0
  matrix:
    - DESTINATION="OS=14.2,name=iPhone 8" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64" SCHEME="$MACOS_FRAMEWORK_SCHEME" SDK="$MACOS_SDK"
before_install:
  - bundle install
  - brew update
  - gem install xcpretty --no-document --quiet
  - brew outdated swiftlint || brew upgrade swiftlint
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
  - export DANGER_GITHUB_API_TOKEN
  - bundle exec danger

after_success:
   - sleep 10 # Workaround for https://github.com/travis-ci/travis-ci/issues/4725
   - bash <(curl -s https://codecov.io/bash) -J 'OAuthSwift'

